//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Melomash.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Melomash.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить уровень.
        /// </summary>
        public static string AddLevel {
            get {
                return ResourceManager.GetString("AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меломания.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите сбросить весь свой прогресс в этой игре?.
        /// </summary>
        public static string AreYouSureReset {
            get {
                return ResourceManager.GetString("AreYouSureReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться назад.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить за .
        /// </summary>
        public static string BuyFor {
            get {
                return ResourceManager.GetString("BuyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена операции.
        /// </summary>
        public static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите купить уровень &quot;{0}&quot; за {1} монет?.
        /// </summary>
        public static string ConfirmBuyMessage {
            get {
                return ResourceManager.GetString("ConfirmBuyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение покупки.
        /// </summary>
        public static string ConfirmBuyTitle {
            get {
                return ResourceManager.GetString("ConfirmBuyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить уровень?.
        /// </summary>
        public static string ConfirmToDelete {
            get {
                return ResourceManager.GetString("ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Составлен список файлов для скачивания! Общий размер файлов - {0} Килобайт. Начать скачивание уровня?.
        /// </summary>
        public static string ConfirmToDownload {
            get {
                return ResourceManager.GetString("ConfirmToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши поздравления!.
        /// </summary>
        public static string Congrats {
            get {
                return ResourceManager.GetString("Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правильный ответ.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верно!.
        /// </summary>
        public static string CorrectText {
            get {
                return ResourceManager.GetString("CorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить уровень.
        /// </summary>
        public static string DeleteLevelContext {
            get {
                return ResourceManager.GetString("DeleteLevelContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание файла {0} завершено.
        /// </summary>
        public static string DownloadFinish {
            get {
                return ResourceManager.GetString("DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание уровня &quot;{0}&quot;.
        /// </summary>
        public static string DownloadOperationDeclare {
            get {
                return ResourceManager.GetString("DownloadOperationDeclare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Убрать лишние буквы.
        /// </summary>
        public static string ExtraSymbHint {
            get {
                return ResourceManager.GetString("ExtraSymbHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать первую букву.
        /// </summary>
        public static string FirstSymbHint {
            get {
                return ResourceManager.GetString("FirstSymbHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно прервать загрузку.
        /// </summary>
        public static string ImposToAbort {
            get {
                return ResourceManager.GetString("ImposToAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недоступно интернет-соединение. Проверьте параметры телефона или повторите попытку позже!.
        /// </summary>
        public static string InternetIsNotWorking {
            get {
                return ResourceManager.GetString("InternetIsNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Происходит загрузка.
        /// </summary>
        public static string IsLoading {
            get {
                return ResourceManager.GetString("IsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой уровень у Вас уже есть в базе!.
        /// </summary>
        public static string LevelExists {
            get {
                return ResourceManager.GetString("LevelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя уровня:.
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровни.
        /// </summary>
        public static string LevelsList {
            get {
                return ResourceManager.GetString("LevelsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка завершена.
        /// </summary>
        public static string LoadingComplete {
            get {
                return ResourceManager.GetString("LoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string LoadingString {
            get {
                return ResourceManager.GetString("LoadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти в список уровней.
        /// </summary>
        public static string NavigateToLevelsList {
            get {
                return ResourceManager.GetString("NavigateToLevelsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению,лишних букв нет! Эта подсказка бесполезна.
        /// </summary>
        public static string NoExtraSymbs {
            get {
                return ResourceManager.GetString("NoExtraSymbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно монет. Требуется ещё {0}. Пополнить баланс?.
        /// </summary>
        public static string NotEnoughCoins {
            get {
                return ResourceManager.GetString("NotEnoughCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщество группы ВКОНТАКТЕ.
        /// </summary>
        public static string OfficialCommunityVK {
            get {
                return ResourceManager.GetString("OfficialCommunityVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на начальный экран.
        /// </summary>
        public static string PinStartContext {
            get {
                return ResourceManager.GetString("PinStartContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ....
        /// </summary>
        public static string Pushme {
            get {
                return ResourceManager.GetString("Pushme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить прогресс.
        /// </summary>
        public static string Reset_progress {
            get {
                return ResourceManager.GetString("Reset_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить отзыв.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение к серверу.
        /// </summary>
        public static string ServerConnect {
            get {
                return ResourceManager.GetString("ServerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАСТРОЙКИ.
        /// </summary>
        public static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассказать в Facebook.
        /// </summary>
        public static string ShareFacebook {
            get {
                return ResourceManager.GetString("ShareFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассказать в Twitter.
        /// </summary>
        public static string ShareTwitter {
            get {
                return ResourceManager.GetString("ShareTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассказать в ВК.
        /// </summary>
        public static string ShareVK {
            get {
                return ResourceManager.GetString("ShareVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звуки клавиш.
        /// </summary>
        public static string Sounds_checkbox {
            get {
                return ResourceManager.GetString("Sounds_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начинаю скачивание файла {0}.
        /// </summary>
        public static string StartToDownload {
            get {
                return ResourceManager.GetString("StartToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный трек сейчас недоступен! Для разблокировки используйте подсказки!.
        /// </summary>
        public static string ThirdTrackLocked {
            get {
                return ResourceManager.GetString("ThirdTrackLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верный ответ.
        /// </summary>
        public static string TrueAnswerHint {
            get {
                return ResourceManager.GetString("TrueAnswerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это действительно.
        /// </summary>
        public static string TruelyItIs {
            get {
                return ResourceManager.GetString("TruelyItIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разблокировать трек.
        /// </summary>
        public static string UnlockThirdTrack {
            get {
                return ResourceManager.GetString("UnlockThirdTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на обновить уровень.
        /// </summary>
        public static string UpdateLevelContext {
            get {
                return ResourceManager.GetString("UpdateLevelContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать в Яндекс.Музыка.
        /// </summary>
        public static string YandexMusic {
            get {
                return ResourceManager.GetString("YandexMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы великолепны!.
        /// </summary>
        public static string YouAreGreat {
            get {
                return ResourceManager.GetString("YouAreGreat", resourceCulture);
            }
        }
    }
}
